MEXICODER3/mexicoder3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mexicoder3.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^soccer/', include('soccer.urls')),
)

MEXICODER3/soccer/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
    url(r'^$', MainView.as_view()),
    url(r'^leagues/$', LeagueView.as_view()),
    url(r'^clubs/$', ClubView.as_view()),
    url(r'^players/$', PlayerView.as_view()),
)

MEXICODER3/soccer/models.py
from django.db import models

POSITIONS = (
    ("GK", "Goal Keeper"),
    ("DF", "Defender"),
    ("DF", "Defender"),
    ("MF", "Midfielder"),
    ("FW", "Forward"),
)

class League(models.Model):
    name = models.CharField(max_length = 100)
    start_date = models.DateField()
    end_date = models.DateField(null = True, blank = True)
    edition = models.IntegerField()
    #TODO: add more fields

    def __unicode__(self):
        return self.name

class Club(models.Model):
    name = models.CharField(max_length = 100)
    leagues = models.ManyToManyField(League)
    #TODO: add more fields

    def coach(self):
        """
        Returns the coach (if exist) of curren Team
        """
        try:
            return Coach.objects.get(club = self.id).full_name()
        except:
            return "No coach yet"

    def __unicode__(self):
        return self.name

class Person(models.Model):
    """
    This model will be used for reusing code for Coach and Player
    """
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    country = models.CharField(max_length = 50)
    club = models.ForeignKey(Club)
    #TODO: add more fields

    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return self.full_name()

class Coach(Person):
    start_date = models.DateField()
    end_date = models.DateField(null = True, blank = True)
    #TODO: add more fields

class Player(Person):
    rating = models.IntegerField(default = 0)
    foot = models.CharField(choices = (("R", "Right"), ("L", "Left")), max_length = 2)
    pace = models.IntegerField(default = 0)
    shooting = models.IntegerField(default = 0)
    passing = models.IntegerField(default = 0)
    dribbling = models.IntegerField(default = 0)
    defending = models.IntegerField(default = 0)
    heading = models.IntegerField(default = 0)
    height = models.IntegerField(default = 0)
    age = models.IntegerField(default = 0)
    position = models.CharField(help_text = "Select the best position of this player", choices = POSITIONS, max_length = 2)
    #TODO: add more fields

MEXICODER3/soccer/views.py
from django.db.models import Q
from django.shortcuts import render, render_to_response
from django.views.generic import View
from models import *

class MainView(View):
    template_name = 'home.html'

    def get(self, request):
        # <view logic>
        options = (
            ("leagues", "Leagues"),
            ("clubs", "Clubs"),
            ("players", "Players"),
        )
        return render(request, self.template_name, {
            "title": "Home",
            "options": options
        })

class MyView(View):

    def search_by_name(self, name):
        return self.model.objects.filter(name__contains=name)

class LeagueView(MyView):
    template_name = 'league.html'
    title = "Leagues"
    model = League

    def get(self, request):
        league_name = request.GET.get("league")
        if league_name:
            leagues = self.search_by_name(league_name)
        else:
            leagues = self.model.objects.all()
        return render(request, self.template_name, {
            "title": self.title,
            "leagues": leagues,
            "model": self.model.__name__.lower()
        })

class ClubView(MyView):
    template_name = 'club.html'
    title = "Clubs"
    model = Club

    def get(self, request):
        club_name = request.GET.get("club")
        if club_name:
            clubs = self.search_by_name(club_name)
        else:
            clubs = self.model.objects.all()
        return render(request, self.template_name, {
            "title": self.title,
            "clubs": clubs,
            "model": self.model.__name__.lower()
        })

class PlayerView(View):
    template_name = 'player.html'
    title = "player"
    model = Player

    def search(self, player_name):
        return self.model.objects.filter(Q(first_name__contains=player_name) | Q(last_name__contains=player_name))

    def get(self, request):
        player_name = request.GET.get("player")
        if player_name:
            players = self.search(player_name)
        else:
            players = self.model.objects.all()
        return render(request, self.template_name, {
            "title": self.title,
            "players": players,
            "model": self.model.__name__.lower()
        })

MEXICODER3/soccer/templates/base.html
<html>
    <head>
        <title>{{ title }}</title>
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <h1>{{ title }}</h1>
        <div>{% block content %}{% endblock %}</div>
        <h3><!--footer--></h3>
    </body>
</html>

MEXICODER3/soccer/templates/base_search.html
{% extends "base.html" %}
{% block extra_head %}
    <script type="text/javascript">
        function search() {
            {{ model }}_name = document.getElementById("{{ model }}_name").value;
            document.getElementById("{{ model }}_name").value = "";
            window.location = "?{{ model }}="+{{ model }}_name;
        }
    </script>
{% endblock %}
{% block content %}
Search for {{ model }}: <input type="text" id="{{ model }}_name" name="{{ model }}_name" value="">
<input type="button" value="Search" onclick="search()">
    {% block extra_content %}
    {% endblock %}
{% endblock %}

MEXICODER3/soccer/templates/club.html
{% extends "base_search.html" %}
{% block extra_content %}
{% if clubs %}
<table>
    <thead>
        <tr>
            <th>Club</th>
            <th>Coach</th>
        </tr>
    </thead>
    <tbody>
        {% for club in clubs %}
        <tr>
            <td>{{ club.name }}</td>
            <td>{{ club.coach }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h2>No clubs found</h2>
{% endif %}
{% endblock %}

MEXICODER3/soccer/templates/home.html
{% extends "base.html" %}
{% block content %}
<p>Welcome to our mexicoder soccer test, check or menu</p>
<ul>
    {% for option in options %}
        <li><a href="{{ option.0 }}">{{ option.1 }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

MEXICODER3/soccer/templates/league.html
{% extends "base_search.html" %}
{% block extra_content %}
{% if leagues %}
<table>
    <thead>
        <tr>
            <th>League</th>
            <th>Edition</th>
            <th>Begin</th>
            <th>End</th>
        </tr>
    </thead>
    <tbody>
        {% for league in leagues %}
        <tr>
            <td>{{ league.name }}</td>
            <td>{{ league.edition }}</td>
            <td>{{ league.start_date }}</td>
            <td>{% if league.end_date %}{{ league.end_date }}{% else %}Not finished{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h2>No leagues found</h2>
{% endif %}
{% endblock %}

MEXICODER3/soccer/templates/player.html
{% extends "base_search.html" %}
{% block extra_content %}
{% if players %}
<table>
    <thead>
        <tr>
            <th>Player</th>
            <th>Country</th>
            <th>Rating</th>
            <th>Foot</th>
            <th>Pace</th>
            <th>Shooting</th>
            <th>Passing</th>
            <th>Dribbling</th>
            <th>Defending</th>
            <th>Heading</th>
            <th>Height</th>
            <th>Age</th>
            <th>Position</th>
        </tr>
    </thead>
    <tbody>
        {% for player in players %}
        <tr>
            <td>{{ player.full_name }}</td>
            <td>{{ player.country }}</td>
            <td>{{ player.rating }}</td>
            <td>{{ player.get_foot_display }}</td>
            <td>{{ player.pace }}</td>
            <td>{{ player.shooting }}</td>
            <td>{{ player.passing }}</td>
            <td>{{ player.dribbling }}</td>
            <td>{{ player.defending }}</td>
            <td>{{ player.heading }}</td>
            <td>{{ player.height }}</td>
            <td>{{ player.age }}</td>
            <td>{{ player.get_position_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h2>No players found</h2>
{% endif %}
{% endblock %}